### ISSUE TITLE
fail to get into the login website

### ISSUE THREAD

**Issue by zhouliang-yu** [philipzhux/enroll-monster#1]
Hey Philip, thx so much for sharing your code. 
I go very smoothly following the first several instructions.
There is a slight issue when I click the link in the `preparation.` I fail to go to the `login` page of sis.

I think this is because the link is not the latest version of the sis login page.

**Comment by philipzhux** [comment]
fixed

**Comment by zhouliang-yu** [comment]
> fixed

thx!
